all: generate-text.png hello-world.png http-api-dynamo-db.png sqs-lambda.png
generate-text.png:
	python generate-text.py
hello-world.png:
	python hello-world.py
http-api-dynamo-db.png:
	python http-api-dynamo-db.py
sqs-lambda.png:
	python sqs-lambda.py
clean:
	rm *.png